name: challenges
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - pillow
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
